/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardDeliverablesRouteImport } from './routes/dashboard.deliverables'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsSlugRouteImport } from './routes/dashboard.projects.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliverablesRoute = DashboardDeliverablesRouteImport.update({
  id: '/deliverables',
  path: '/deliverables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsSlugRoute = DashboardProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/deliverables': typeof DashboardDeliverablesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$slug': typeof DashboardProjectsSlugRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/deliverables': typeof DashboardDeliverablesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/$slug': typeof DashboardProjectsSlugRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/portfolio': typeof PortfolioRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/deliverables': typeof DashboardDeliverablesRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/$slug': typeof DashboardProjectsSlugRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/deliverables'
    | '/dashboard/messages'
    | '/dashboard/reviews'
    | '/dashboard/'
    | '/dashboard/projects/$slug'
    | '/dashboard/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/login'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/deliverables'
    | '/dashboard/messages'
    | '/dashboard/reviews'
    | '/dashboard'
    | '/dashboard/projects/$slug'
    | '/dashboard/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/login'
    | '/portfolio'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/dashboard/deliverables'
    | '/dashboard/messages'
    | '/dashboard/reviews'
    | '/dashboard/'
    | '/dashboard/projects/$slug'
    | '/dashboard/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortfolioRoute: typeof PortfolioRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/deliverables': {
      id: '/dashboard/deliverables'
      path: '/deliverables'
      fullPath: '/dashboard/deliverables'
      preLoaderRoute: typeof DashboardDeliverablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/projects'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/$slug': {
      id: '/dashboard/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/dashboard/projects/$slug'
      preLoaderRoute: typeof DashboardProjectsSlugRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDeliverablesRoute: typeof DashboardDeliverablesRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProjectsSlugRoute: typeof DashboardProjectsSlugRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDeliverablesRoute: DashboardDeliverablesRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProjectsSlugRoute: DashboardProjectsSlugRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PortfolioRoute: PortfolioRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
